version: "3.8"

services:
  database:
    image: postgres:14
    container_name: service-database
    ports:
      - '127.0.0.1:5430:5432'
    volumes:
      - psql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=preprod_beapuls
    expose:
      - 5430

  # api:
  #   build:
  #     context: ./
  #   container_name: service-api
  #   working_dir: /var/www
  #   networks:
  #     - app-network
  #   ports:
  #     - '127.0.0.1:3333:3333'


volumes:
  psql-data:

  
# networks:
#   app-network:
#     driver: bridge