# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Checks CDelivery

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.10.0]
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Build for Production
        run: npm run build

      - name: Create a GitHub Releases
        run: cd build && npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}