name: CDeployment

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0  # Fetch all history to get tags
          ref: deploy  

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Get latest tag
        shell: bash
        id: get_tag
        run: echo "::set-output name=TAG_NAME::$(git describe --tags $(git rev-list --tags --max-count=1) | tr -d 'v')"
            
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/beapuls-api:${{ steps.get_tag.outputs.TAG_NAME }}

    