# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Github Actions

on:
  push:
    branches:
    - deploy
  pull_request:
    branches:
    - deploy

jobs:
  workflow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.10.0]
  ci:
    uses: /BeaPuls/beapuls-api-v6/.github/workflows/CI.yml@deploy
  cdelivery:
    uses: /BeaPuls/beapuls-api-v6/.github/workflows/CDeployment.yml@deploy
